"""empty message

Revision ID: e71268c2aa99
Revises: 466cf2f35d67
Create Date: 2018-01-26 16:43:07.514311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71268c2aa99'
down_revision = '466cf2f35d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('ppin', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'ppin')
    # ### end Alembic commands ###
